<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01. a_HELP</name>
   <tag></tag>
   <elementGuidId>2632ebaf-ef37-416d-8459-bb67ace51854</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;cm-g-gnb gnb&quot;]/nav[@class=&quot;gb-gnb&quot;]/div[@class=&quot;gb-gnb__bar&quot;]/div[@class=&quot;gb-gnb__bar-inner&quot;]/div[@class=&quot;gb-gnb__sub&quot;]/ul[@class=&quot;gb-gnb__sub-nav&quot;]/li[@class=&quot;s-depth1-wrap&quot;]/a[@class=&quot;s-btn-toggler js-toggler js-depth1-link&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-omni</name>
      <type>Main</type>
      <value>support</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>售后服务</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-btn-toggler js-toggler js-depth1-link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link-info</name>
      <type>Main</type>
      <value>true^http://www.samsung.com/cn/support/^</value>
   </webElementProperties>
</WebElementEntity>
