<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>29.li_KT</name>
   <tag></tag>
   <elementGuidId>bdfcdeb8-5046-4f27-9001-005c3db32adb</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;js-fs-blank&quot;]/div[contains(@class,&quot;filter-sort&quot;)]/div[@class=&quot;filter-sort__head&quot;]/div[@class=&quot;filter-sort__xscroll-wrap&quot;]/div[@class=&quot;filter-sort-applied&quot;]/ul[@class=&quot;applied-list&quot;]/li[3]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KT</value>
   </webElementProperties>
</WebElementEntity>
