<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>05. button</name>
   <tag></tag>
   <elementGuidId>c95625ad-5318-442e-92c2-2aa96fc1e482</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listProducts1&quot;)/div[@class=&quot;product-details&quot;]/div[@class=&quot;product-info&quot;]/div[@class=&quot;product-info-data&quot;]/div[@class=&quot;family-option&quot;]/div[@class=&quot;customizations color&quot;]/ul[@class=&quot;customizations-option&quot;]/li[2]/button[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:fmyChipchange('0','1','listProducts1','#000000','COLOR','CARRIER:移动定制版,COLOR:#ffffff','list');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>black</value>
   </webElementProperties>
</WebElementEntity>
