<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10. img_js-img-src_02</name>
   <tag></tag>
   <elementGuidId>0bac30dd-0852-4a6c-bc82-b704f7f90104</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src-mobile</name>
      <type>Main</type>
      <value>//images.samsung.com/is/image/samsung/p5/uk/offers/freegears3strap/GearS3_FreeStrap_offer_kv_mobile-2.jpg?$ORIGIN_JPG$</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;offer-list parsys&quot;]/div[@class=&quot;of-g-offer-list-header section&quot;]/section[@class=&quot;sc-offer-header&quot;]/div[@class=&quot;s-slick js-offer-carousel-div slick-initialized slick-slider slick-dotted&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-current slick-active&quot;]/div[@class=&quot;s-header-wrap&quot;]/div[@class=&quot;s-bg-wrap&quot;]/img[@class=&quot;js-img-src&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//images.samsung.com/is/image/samsung/p5/uk/offers/freegears3strap/GearS3_FreeStrap_offer_kv_desktop-2.jpg?$ORIGIN_JPG$</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src-pc</name>
      <type>Main</type>
      <value>//images.samsung.com/is/image/samsung/p5/uk/offers/freegears3strap/GearS3_FreeStrap_offer_kv_desktop-2.jpg?$ORIGIN_JPG$</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1440</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Buy a Gear S3 and claim a free strap and additional wireless charging dock</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-img-src</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>640</value>
   </webElementProperties>
</WebElementEntity>
