<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_cbtn</name>
   <tag></tag>
   <elementGuidId>08748534-2f86-4c1d-865c-7d99f607054c</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/section[@class=&quot;support-z&quot;]/div[@class=&quot;pdp-contents&quot;]/div[@class=&quot;par parsys&quot;]/div[@class=&quot;section sp-g-pdp-usefullink&quot;]/div[@class=&quot;pdp-row acont bg1&quot;]/div[@class=&quot;rp-guide-w&quot;]/div[@class=&quot;pixed-in&quot;]/ul[@class=&quot;rp-guide-list&quot;]/li[1]/div[@class=&quot;gitem&quot;]/div[@class=&quot;alignc&quot;]/a[@class=&quot;cbtn&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/uk/support/warranty</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cbtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
   </webElementProperties>
</WebElementEntity>
