<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_primary-link parent-level-li</name>
   <tag></tag>
   <elementGuidId>35a99846-6fb3-4dbf-bf30-bb33350ade1c</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;urn:sony:module:one_sony_tout_carousel:187035028422272246679302&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;one-sony-carousel secondary-tout&quot;]/div[@class=&quot;st-container&quot;]/div[@class=&quot;st-container-inner sony-carousel-active&quot;]/div[@class=&quot;st-content&quot;]/div[@class=&quot;st-grid gwt-module&quot;]/div[@class=&quot;st-item content-4 span12&quot;]/article[1]/a[@class=&quot;primary-link parent-level-link&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>//www.sony.co.kr/electronics/interchangeable-lens-cameras/ilce-9?cpint=HOMEPAGE_THELATEST4SPAN_ILCE9_5431</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-new-win</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-link parent-level-link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
   </webElementProperties>
</WebElementEntity>
