<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_01</name>
   <tag></tag>
   <elementGuidId>817c8d97-1b5c-4caf-a551-6ded3623d16b</elementGuidId>
   <imagePath>../../Desktop/develop/etc/images/sec-galaxy-s8_01.jpg</imagePath>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-num</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s7_mixedmediaview_code0&quot;)/img[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//images.samsung.com/is/image/samsung/sec-galaxy-s8-g950-sm-g950nzkaktc-frontblack-61719473?$PD_GALLERY_JPG$</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>미드나잇 블랙 앞면</value>
   </webElementProperties>
</WebElementEntity>
