<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>07.span_filter-sort__inp-checkbox</name>
   <tag></tag>
   <elementGuidId>f556a8da-9959-42c3-9879-da5413757bc3</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;product-filter-grid&quot;]/div[@class=&quot;product-filter-grid__left&quot;]/div[@class=&quot;filter-sort__fix-wrap&quot;]/div[@class=&quot;filter-sort__list-wrap&quot;]/div[@class=&quot;filter-sort__list active&quot;]/div[@class=&quot;filter-sort__item&quot;]/ul[1]/li[4]/div[@class=&quot;filter-sort__checkbox&quot;]/span[@class=&quot;filter-sort__inp-checkbox&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-acc-checkbox</name>
      <type>Main</type>
      <value>checkbox-series03z04</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-sort__inp-checkbox hover</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-acc-onclass</name>
      <type>Main</type>
      <value>active</value>
   </webElementProperties>
</WebElementEntity>
