<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_PC_01</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2017-07-04T13:33:11</lastRun>
   <mailRecipient>mulan101@gmail.com;je-ho.han@kr.ey.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ae51cc88-2d5d-4197-9d97-b516cd1cb86a</testSuiteGuid>
   <testCaseLink>
      <guid>df184ba2-89ec-4e1d-825d-8aa11bcdc9b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SCENARIO_TEST/KOREA/PC/TC_pc_01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4aac2508-eaf8-4342-875f-a1a4ea09bc53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c296bcab-d309-47a8-94d0-6d0dc34b034d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
